version: '3'

services:
  appgt:
    build:
      context: ./appgt
    ports:
      - "8080:8080"
    networks:
      - apptext
    container_name: apigateway
    #depends_on:
      #- load_balancer
      #- registry_discovery

  load_balancer:
    build:
      context: ./load_balancer
    ports:
      - "9000:80"
    networks:
      - apptext

  registry_discovery:
    build:
      context: ./registry_discovery
    ports:
      - "8500:8500"  # Puerto para la interfaz web de Consul
    command: agent -dev -client 0.0.0.0  # Comando para arrancar el servicio Consul en modo desarrollo
    networks:
      - apptext
networks:
  apptext:
    driver: bridge