version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - consul_network
    depends_on:
      - consul
    environment:
      - CONSUL_HOST=consul
      - NGINX_IP=frontend

  consul:
    build:
      context: ./consul
      dockerfile: Dockerfile
    ports:
      - "8500:8500"
      - "8600:8600"
    networks:
      - consul_network

  register-service:
    build:
      context: ./register-service
      dockerfile: Dockerfile
    networks:
      - consul_network
    depends_on:
      - consul
    environment:
      - CONSUL_HOST=consul
  
  haproxy:
    build:
      context: ./load_balancer
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - consul_network
    depends_on:
      - frontend
      - consul

networks:
  consul_network:
    driver: bridge
